name: 'Workflow - Terraform Destroy Manual'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name (e.g. feature/vpc-eks-modules)"
        required: true
        default: "feature/vpc-eks-modules"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: "dev"

jobs:
  destroy:
    runs-on: ubuntu-22.04
    environment: dev
    env:
      TF_VAR_sso_admin_arn: ${{ vars.SSO_ADMIN_ARN }}
      TF_VAR_github_ci_role_arn: ${{ vars.CI_ROLE_ARN }}
      TF_VAR_github_tf_role_arn: ${{ vars.TF_ROLE_ARN }}
    defaults:
      run:
        working-directory: ./roots/devops-project-main
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ github.event.inputs.branch }}.tfstate"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars
